# permissions for end users to view nexus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nexus-viewer-role
rules:
- apiGroups:
  - cache.foundry.io
  resources:
  - nexus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.foundry.io
  resources:
  - nexus/status
  verbs:
  - get
